[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a40b273f890>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6ef3217a3f63e0ed1c90c27d83660e02/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a40b26b2cf0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6ef3217a3f63e0ed1c90c27d83660e02/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a40b26b1850>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6ef3217a3f63e0ed1c90c27d83660e02/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a40b27400e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6ef3217a3f63e0ed1c90c27d83660e02/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a40b27402f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6ef3217a3f63e0ed1c90c27d83660e02/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a40b2740c80>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6ef3217a3f63e0ed1c90c27d83660e02/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a40b27412e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6ef3217a3f63e0ed1c90c27d83660e02/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a40b2741580>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6ef3217a3f63e0ed1c90c27d83660e02/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a40b27417f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6ef3217a3f63e0ed1c90c27d83660e02/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a40b2741df0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6ef3217a3f63e0ed1c90c27d83660e02/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a40b2742060>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6ef3217a3f63e0ed1c90c27d83660e02/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a40b2742210>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6ef3217a3f63e0ed1c90c27d83660e02/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a40b27422a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6ef3217a3f63e0ed1c90c27d83660e02/title
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a40b2742480>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6ef3217a3f63e0ed1c90c27d83660e02/title
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a40b2742660>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6ef3217a3f63e0ed1c90c27d83660e02/title
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a40b2742a20>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6ef3217a3f63e0ed1c90c27d83660e02
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a40b260ac90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6ef3217a3f63e0ed1c90c27d83660e02
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a40b2609b50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6ef3217a3f63e0ed1c90c27d83660e02
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a40b2609370>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6ef3217a3f63e0ed1c90c27d83660e02
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a40b2609d60>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6ef3217a3f63e0ed1c90c27d83660e02
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a40b260a300>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6ef3217a3f63e0ed1c90c27d83660e02