[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b4e64cab860>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/76877203102c12085e4ca0108d16677c/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b4e64cabb90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/76877203102c12085e4ca0108d16677c/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b4e64caa630>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/76877203102c12085e4ca0108d16677c/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b4e64cec050>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/76877203102c12085e4ca0108d16677c/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b4e64cec2c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/76877203102c12085e4ca0108d16677c/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b4e64cec560>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/76877203102c12085e4ca0108d16677c/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b4e64cef980>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/76877203102c12085e4ca0108d16677c
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b4e64cef530>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/76877203102c12085e4ca0108d16677c
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b4e64cee600>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/76877203102c12085e4ca0108d16677c
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b4e64cef290>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/76877203102c12085e4ca0108d16677c
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b4e64cef8f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/76877203102c12085e4ca0108d16677c
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b4e64cefbf0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/76877203102c12085e4ca0108d16677c