[32mINFO    [0m root:setupMicroplanQA.py:32 ***************Opening URL: https://unified-qa.digit.org/microplan-ui/employee/user/login*****************
[32mINFO    [0m root:setupMicroplanQA.py:34 *****************Performing login actions*******************
[32mINFO    [0m root:setupMicroplanQA.py:43 ***********Logging successful***************
[32mINFO    [0m root:setupMicroplanQA.py:54 **********Microplan name initiated*****************
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b5332bc0260>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6f94b7adc882e95adc8f78179f88a660/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b5332bc0440>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6f94b7adc882e95adc8f78179f88a660/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b5332bc0620>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6f94b7adc882e95adc8f78179f88a660/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b5332bc28d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6f94b7adc882e95adc8f78179f88a660
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b5332bc2660>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6f94b7adc882e95adc8f78179f88a660
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b5332bc2d20>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6f94b7adc882e95adc8f78179f88a660
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b5332bc3290>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6f94b7adc882e95adc8f78179f88a660
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b5332bc38f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6f94b7adc882e95adc8f78179f88a660
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b5332bc3c80>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6f94b7adc882e95adc8f78179f88a660