[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a4cb8987ad0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1fec19d746d051ea19e228b2c89767da/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a4cb8b1b650>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1fec19d746d051ea19e228b2c89767da/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a4cb8987c50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1fec19d746d051ea19e228b2c89767da/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a4cb89df0e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1fec19d746d051ea19e228b2c89767da
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a4cb89de0c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1fec19d746d051ea19e228b2c89767da
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a4cb89dd4c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1fec19d746d051ea19e228b2c89767da
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a4cb89dcdd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1fec19d746d051ea19e228b2c89767da
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a4cb89de840>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1fec19d746d051ea19e228b2c89767da
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a4cb89debd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1fec19d746d051ea19e228b2c89767da