[32mINFO    [0m root:setupMicroplan2.py:38 Opening URL: https://health-demo.digit.org/microplan-ui/employee/user/login
[32mINFO    [0m root:setupMicroplan2.py:43 Performing login actions
[32mINFO    [0m root:setupMicroplan2.py:53 Login successful, title verified
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7906451f8d70>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9effb4580a5f417583499f6900b9f9ba
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7906451f8e30>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9effb4580a5f417583499f6900b9f9ba
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7906451f8fe0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9effb4580a5f417583499f6900b9f9ba