[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x792df5c2c350>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6115157df3a527223d50aa8197b3796e/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x792df5da2270>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6115157df3a527223d50aa8197b3796e/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x792df5c2c590>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6115157df3a527223d50aa8197b3796e/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x792df5c2cb60>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6115157df3a527223d50aa8197b3796e/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x792df5c2cdd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6115157df3a527223d50aa8197b3796e/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x792df5c2d040>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6115157df3a527223d50aa8197b3796e/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x792df5c2d640>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6115157df3a527223d50aa8197b3796e/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x792df5c2d8b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6115157df3a527223d50aa8197b3796e/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x792df5c2db20>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6115157df3a527223d50aa8197b3796e/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x792df5c2fe90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6115157df3a527223d50aa8197b3796e
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x792df5c2f890>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6115157df3a527223d50aa8197b3796e
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x792df5c2f7a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6115157df3a527223d50aa8197b3796e
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x792df5af4200>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6115157df3a527223d50aa8197b3796e
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x792df5af4560>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6115157df3a527223d50aa8197b3796e
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x792df5af4740>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6115157df3a527223d50aa8197b3796e