[32mINFO    [0m root:setupMicroplanQA.py:32 ***************Opening URL: https://health-demo.digit.org/microplan-ui/employee/user/login*****************
[32mINFO    [0m root:setupMicroplanQA.py:34 *****************Performing login actions*******************
[32mINFO    [0m root:setupMicroplanQA.py:43 ***********Logging successful***************
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74a0eeb928d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/0715209da77b7ebb229c643252ea9b5d
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74a0eeb90200>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/0715209da77b7ebb229c643252ea9b5d
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74a0eeb904d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/0715209da77b7ebb229c643252ea9b5d